name: Fetch Builds from Supabase

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */12 * * *'  # Every day at midnight UTC

jobs:
  fetch-builds:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install Python dependencies
        run: |
          pip install requests

      - name: Fetch builds index
        run: |
          python3 fetch_builds.py

      - name: Download new build rounds
        run: |
          python3 builds-download/scrape-builds.py

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update build data from Supabase
          file_pattern: 'builds.json builds-download/build_rounds_data/*.json'
